#!/usr/bin/env python3
"""Generate speech_note/speech_note/Localizable.xcstrings from Chinese source keys."""

from __future__ import annotations

import json
from pathlib import Path

# Chinese source string -> English. Keys match SwiftUI Text("…") / L("…") literals.
TRANSLATIONS: dict[str, str] = {
    # App / navigation
    "语音便签": "Voice Notes",
    "听记": "VoiceContext",
    "全部录音": "All Recordings",
    "我的": "Me",
    "设置与偏好": "Settings",
    "设置": "Settings",
    "完成": "Done",
    "取消": "Cancel",
    "确认": "Confirm",
    "删除": "Delete",
    "保存": "Save",
    "保存中…": "Saving…",
    "关闭": "Close",
    "返回": "Back",
    "继续": "Continue",
    "分享": "Share",
    "导出": "Export",
    "导入": "Import",
    "筛选": "Filter",
    "已筛选": "Filtered",
    "搜索": "Search",
    "重置": "Reset",
    "应用筛选": "Apply",
    "全选": "Select All",
    "取消全选": "Deselect All",
    "多选模式": "Select Multiple",
    "个人中心": "Account",
    "转写与调度": "Transcription",
    "管理": "Manage",
    "功能菜单": "Menu",
    "记录": "Recordings",
    "工作台与导入": "Workspace & Import",
    # Language
    "界面语言": "App Language",
    "语言 / Language": "Language",
    "语言模式": "Language Mode",
    "跟随系统 / Follow System": "Follow System",
    "简体中文": "简体中文",
    "中文": "Chinese",
    "中英双语": "Chinese & English",
    "粤语": "Cantonese",
    "英语": "English",
    "日语": "Japanese",
    "韩语": "Korean",
    "自动识别": "Auto Detect",
    "自动": "Auto",
    "转写": "Transcription",
    "默认为中文。自动识别会让模型在中文、粤语、英语、日语和韩语之间判断。仅影响之后开始的新录音与新导入；已完成文稿不会自动重跑。": "Default is Chinese. Chinese & English lets the model choose between Chinese and English; you can also pin Cantonese, English, Japanese, or Korean. Applies only to new recordings and imports — finished transcripts are not rerun.",
    "默认为中文。中英双语会让模型在中文和英语之间自动判断；也可指定粤语、英语、日语或韩语。仅影响之后开始的新录音与新导入；已完成文稿不会自动重跑。": "Default is Chinese. Chinese & English auto-detects between Chinese and English; you can also pin Cantonese, English, Japanese, or Korean. Applies only to new recordings and imports — finished transcripts are not rerun.",
    "录音时实时转写": "Transcribe while recording",
    "开启后，每段录音一结束就开始转写。关闭后，等你停止录音再排队，录音过程更省电、也少抢性能。": "When on, each finished segment starts transcribing immediately. When off, work waits until you stop, which uses less power during capture.",
    "允许转写在后台继续": "Allow transcription in the background",
    "仅在你停止录音、导入或手动重试后申请。语音仍在本机处理；系统可因电量、发热或你的取消操作中止，之后回到应用会继续。": "Requested after you stop, import, or retry. Speech stays on-device. iOS may pause for battery, heat, or cancellation; returning to the app continues.",
    "iOS 26 以上可允许长转写在后台继续；当前系统会在回到应用后自动续跑。": "iOS 26 and later can keep long transcriptions running in the background. On this system, work continues when you return to the app.",
    # Home / list
    "搜索转写内容与标签…": "Search transcripts and tags…",
    "搜索转写内容": "Search transcripts",
    "清除搜索": "Clear Search",
    "没有找到相关转写": "No matching transcripts",
    "试试其他关键词，或清空搜索查看全部记录。": "Try different keywords, or clear search to see all recordings.",
    "正在搜索…": "Searching…",
    "暂无录音记录": "No Recordings Yet",
    "还没有记录": "No recordings yet",
    "没有符合筛选的记录": "No recordings match this filter",
    "开始录音，保存一个念头或一次对话。也可从左上角导入文件或相册视频。": "Start a recording to save a thought or a conversation. You can also import files or Photos videos from the menu.",
    "换一个时间范围或筛选条件，或开始一条新录音。": "Try a different date range or filter, or start a new recording.",
    "轻点底部麦克风开始录音，或从顶部导入音频与视频。": "Tap the mic to start recording, or import audio and video from the menu.",
    "开始录音": "Start Recording",
    "录音进行中": "Recording in Progress",
    "录音进行中，轻点查看": "Recording in progress, tap to view",
    "录音中 · 轻点查看": "Recording · tap to view",
    "未命名录音": "Untitled Recording",
    "未命名会议": "Untitled Meeting",
    "导入音频": "Imported Audio",
    "文件夹": "Folder",
    "全部文件夹": "All Folders",
    "未分类": "Uncategorized",
    "文件夹管理": "Manage Folders",
    "管理文件夹…": "Manage Folders…",
    "新建文件夹": "New Folder",
    "新建文件夹…": "New Folder…",
    "文件夹名称": "Folder Name",
    "创建": "Create",
    "条记录": "recordings",
    "条": "",
    "全部": "All",
    "全部日期": "All Dates",
    "按日期过滤": "Filter by Date",
    "没有记录": "No recordings",
    "过滤到这一天": "Filter to this day",
    "再次点击可清除日期过滤": "Tap again to clear the date filter",
    "清除日期过滤，显示全部录音列表": "Clear the date filter and show all recordings",
    "已选择": "Selected",
    "删除录音": "Delete Recording",
    "批量删除录音": "Delete Recordings",
    "编辑录音名称": "Rename Recording",
    "输入录音名称": "Enter a title",
    "请输入新的录音标题": "Enter a new title for this recording",
    "编辑名称": "Rename",
    "移动到文件夹": "Move to Folder",
    "此录音": "this recording",
    "选择记录类型": "Choose a recording type",
    "个人记录（仅转为文字）": "Personal note (transcript only)",
    "多人会议（识别说话人）": "Meeting (identify speakers)",
    "多人会议会在转写后继续提取声纹；个人记录会跳过这一步。": "Meetings continue into speaker identification after transcription. Personal notes skip that step.",
    "记录录音地点": "Save recording location",
    "允许并记录": "Allow and Save",
    "暂不需要": "Not Now",
    "是否允许 VoiceContext 在录音时自动记录当前发生的地理位置与地址？你也可以稍后在「设置」中随时更改。": "Allow VoiceContext to save the location where a recording starts? You can change this later in Settings.",
    "记录空间未能打开": "Couldn’t open the recording library",
    "地点：": "Location: ",
    # Capture
    "录音中": "Recording",
    "正在录音": "Recording",
    "已暂停": "Paused",
    "中断需注意": "Interrupted",
    "已中断": "Interrupted",
    "可点继续恢复": "Tap continue to resume",
    "正在停止": "Stopping",
    "正在处理": "Processing",
    "已完成": "Completed",
    "转写异常": "Transcription issue",
    "停止": "Stop",
    "停止中": "Stopping",
    "停止录音": "Stop Recording",
    "正在安全停止": "Stopping safely",
    "正在安全保存": "Saving safely",
    "录音继续，转写待前台处理": "Recording continues; transcription waits until you return",
    "分钟级增量转写": "Transcribing each finished minute",
    "可返回记录查看进度": "You can go back and watch progress",
    "最小化": "Minimize",
    "直接开始录音": "Start Recording Now",
    "重试开始录音": "Retry Recording",
    "录音标题": "Title",
    "这是一次会议": "This is a meeting",
    "例：产品周会 / 客户洽谈": "e.g. Weekly sync / client call",
    "基本信息": "Basic Info",
    "当前麦克风正在录音，请先停止": "Microphone is in use. Stop the current recording first.",
    "预选参会客户": "Select Participants",
    "录制中": "Recording",
    "录音已暂停": "Recording paused",
    "录音已中断": "Recording interrupted",
    "录音已结束": "Recording ended",
    "录音状态变化中": "Updating recording state",
    "已中断，等待恢复": "Interrupted, waiting to resume",
    "需要注意": "Needs attention",
    # Status / processing
    "已就绪": "Ready",
    "转写中": "Transcribing",
    "等待解锁": "Pending unlock",
    "待解锁": "Pending unlock",
    "待恢复": "Waiting to resume",
    "注意": "Attention",
    "整理说话人": "Organizing speakers",
    "排队处理中": "Queued",
    "本地处理，可返回应用查看进度": "Processing on-device. Return to the app to see progress.",
    "音频已保存，转写等待解锁": "Audio saved. Transcription waits for unlock.",
    "转写待回到前台后继续": "Transcription will continue when you return",
    "转写待回到前台后继续。": "Transcription will continue when you return.",
    "应用曾退至后台，回到前台后将继续转写。": "The app went to the background. Transcription will continue when you return.",
    "应用退至后台时暂缓，回到前台后将继续转写。": "Paused in the background. Transcription will continue when you return.",
    # Detail
    "录音详情": "Recording",
    "会议详情": "Meeting",
    "编辑": "Edit",
    "音频播放": "Playback",
    "音频暂不可用": "Audio unavailable",
    "快退 15 秒": "Back 15s",
    "快进 15 秒": "Forward 15s",
    "播放": "Play",
    "暂停": "Pause",
    "倍速": "Speed",
    "逐字稿": "Transcript",
    "参会人与声纹": "Speakers",
    "详细信息": "Details",
    "导出与分享": "Export & Share",
    "发言中": "Speaking",
    "复制文本": "Copy",
    "已复制到剪贴板": "Copied to clipboard",
    "已复制文本": "Copied",
    "关联客户档案": "Link to Client",
    "保存为新客户": "Save as New Client",
    "录音元数据": "Recording Metadata",
    "录制时间": "Recorded",
    "录音时长": "Duration",
    "录音语言": "Language",
    "语言模式": "Language Mode",
    "检测语言": "Detected language",
    "录音地点": "Location",
    "录音格式": "Format",
    "存储占用": "Storage",
    "唯一标识": "ID",
    "未记录": "Not recorded",
    "相关文件": "Related Files",
    "暂无相关文件。可添加会议通知、议程、文档或图片。": "No related files yet. Add a meeting note, agenda, document, or image.",
    "确定删除此录音？": "Delete this recording?",
    "删除录音与文稿": "Delete Recording and Transcript",
    "删除后将无法恢复该录音文件及其关联的转写文稿。": "This removes the local audio and transcript. This cannot be undone.",
    "重试": "Retry",
    "重新转写": "Re-transcribe",
    "转写暂缓或遇到异常": "Transcription paused or failed",
    "部分后续分段暂缓或遇到异常": "Some later segments paused or failed",
    "正在生成首个音频分片的转写文稿…": "Transcribing the first audio segment…",
    "每约 60 秒增量转写已关闭分片": "Each finished minute is transcribed as it closes",
    "本场参会人与声纹": "People in this recording",
    "仅显示已识别的单人说话人。": "Only identified individual speakers are shown.",
    "可手工补充未发言或未识别的参会人。确认或关联已有客户会绑定声纹；完成后长按已识别发言人可重新选择。": "You can add people who were present but not identified. Confirming or linking a client binds a voiceprint. Touch and hold a speaker to reassign.",
    "暂无参会人。可手工添加，已识别的发言人也会在此列出。": "No participants yet. Add people manually; identified speakers appear here too.",
    "已参会 · 暂无发言声纹": "Present · no voiceprint yet",
    "已关联: ": "Linked: ",
    "已确认档案": "Confirmed profile",
    "本场已归属 · 未绑定声纹": "Assigned here · no voiceprint yet",
    "疑似匹配": "Possible match",
    "否认匹配": "Reject match",
    "重新选择客户…": "Choose another client…",
    "修改显示名称": "Rename",
    "录音备忘录": "Memo",
    "记录复听想法、转录要点或关键决策…": "Jot down playback notes, key points, or decisions…",
    "自动保存到这条录音": "Saved automatically to this recording",
    "正在保存…": "Saving…",
    "重命名说话人": "Rename Speaker",
    "输入发言人名称": "Enter a speaker name",
    "本场参会人": "Participants",
    "只记录出席事实，不会生成声纹或将其标记为已发言。": "This only records attendance. It does not create a voiceprint or mark them as having spoken.",
    "未找到客户档案": "No client profiles found",
    "新建客户会建立当前说话人的声纹，并加入全局档案。": "A new client enrolls this speaker’s voiceprint into the shared directory.",
    "例如：周会, 客户沟通, 项目评审": "e.g. standup, client call, review",
    "已校对": "Proofread",
    "逐字稿内容（人工编辑后将永久锁定防覆盖）": "Transcript (manual edits lock this text against overwrite)",
    "编辑逐字稿段落": "Edit transcript",
    "编辑此句逐字稿…": "Edit this sentence…",
    "选择此句说话人": "Choose speaker for this sentence",
    "复制单句文本": "Copy sentence",
    "复制全文逐字稿": "Copy full transcript",
    "从此开始播放": "Play from here",
    "将使用现有逐字稿的分句时间戳提取声纹并聚类，原始录音和逐字稿不会被覆盖。": "Voiceprints are extracted from the current sentence timestamps. Original audio and transcript stay unchanged.",
    "只删除 App 中与这条录音关联的副本，不会删除 Files 中的原文件。": "Removes the copy attached in the app. The original file in Files is not deleted.",
    "修改后，录音中属于「": "After this change, every bubble for “",
    "重新识别说话人？": "Re-identify speakers?",
    "重新识别说话人…": "Re-identifying speakers…",
    "识别说话人…": "Identifying speakers…",
    "等待逐字稿识别完成": "Waiting for the transcript to finish",
    "文本尚不可用": "Text not available yet",
    "显示全部发言": "Show all speech",
    "添加文件": "Add File",
    "暂无音频": "No audio",
    "音频时间轴": "Audio timeline",
    "音频波形": "Waveform",
    # Filter
    "筛选记录": "Filter Recordings",
    "时间范围": "Time Range",
    "全部时间": "All Time",
    "今天": "Today",
    "最近 7 天": "Last 7 Days",
    "本月": "This Month",
    "自定义时间": "Custom Range",
    "开始日期": "Start Date",
    "结束日期": "End Date",
    "文件夹分类": "Folder",
    "所属文件夹": "Folder",
    "记录类型": "Type",
    "全部类型": "All Types",
    "个人录音": "Voice Note",
    "会议记录": "Meeting",
    "导入文件与视频": "Imported files & video",
    "导入音视频": "Imported audio/video",
    "重置所有筛选条件": "Reset all filters",
    # Clients
    "客户档案": "Clients",
    "客户档案与声纹": "Clients & Voiceprints",
    "新建客户": "New Client",
    "编辑客户": "Edit Client",
    "姓名": "Name",
    "公司 / 组织": "Company / Organization",
    "职位 / 头衔": "Role / Title",
    "联系方式": "Contact",
    "备注": "Notes",
    "标签（用逗号分隔）": "Tags (comma separated)",
    "声纹档案": "Voiceprint",
    "未采集声纹样本": "No voiceprint samples enrolled",
    "删除客户": "Delete Client",
    "保存客户档案": "Save Client",
    "暂无客户档案": "No clients yet",
    "搜索客户姓名、公司、标签…": "Search name, company, or tags…",
    "录入客户信息并关联声纹，在会议录音与转写时自动识别说话人身份。": "Save a client profile and voiceprint so meetings can identify them automatically.",
    "选择已有客户": "Choose an existing client",
    "新建客户档案…": "New client profile…",
    "关联客户…": "Link client…",
    "编辑客户档案": "Edit client",
    "姓名（必填）": "Name (required)",
    "职位 / 角色": "Role",
    "联系方式（手机或邮箱）": "Contact (phone or email)",
    "标签（多个标签用逗号分隔）": "Tags (comma separated)",
    "标签（用逗号或空格分隔）": "Tags (comma or space separated)",
    "备注信息": "Notes",
    "声纹": "Voiceprint",
    "当前尚未采集到声纹特征样本。在录音详情的「参会人」中确认说话人后，即可将声纹样本自动或手动关联至此客户。": "No voiceprint samples yet. Confirm a speaker in a recording’s Speakers tab to enroll them here.",
    "关联声纹特征": "Link voiceprint",
    "关联后，在会议录音进行离线聚类与识别时，系统将通过声纹特征自动识别此客户。": "After linking, later meetings can identify this client from their voiceprint.",
    # Import / export
    "导入音频文件…": "Import Audio File…",
    "导入相册视频…": "Import Photos Video…",
    "文件：选择 m4a / wav / mp3 等音频": "Files: choose m4a / wav / mp3 and similar audio",
    "照片与视频：抽取视频音轨后导入": "Photos: extract the video soundtrack, then import",
    "语音备忘录请先「存储到文件」，再通过「导入 → 文件」选择。v1 不含 Share Extension。": "For Voice Memos, first Save to Files, then Import → Files. v1 has no Share Extension.",
    "长视频无产品时长上限；导入与转写排队进行，不阻塞新的麦克风录音。": "Long videos have no product duration cap. Import and transcription queue in the background and do not block a new microphone recording.",
    "导入失败：无法读取所选视频": "Import failed: couldn’t read the selected video",
    "导入音频暂不可用。": "Imported audio is temporarily unavailable.",
    "相册视频.mov": "Photos video.mov",
    "常用导出": "Common export",
    "常用格式走系统分享；Markdown / JSON 留给进阶与 Codex。": "Share common formats with the system sheet. Markdown / JSON are for advanced use and Codex.",
    "分享资料包 (.zip)": "Share package (.zip)",
    "导出文本 (.txt)": "Export text (.txt)",
    "导出字幕 (.srt)": "Export captions (.srt)",
    "导出 transcript.md": "Export transcript.md",
    "导出 transcript.json": "Export transcript.json",
    "资料包包含原始录音": "Include original audio in packages",
    "默认关闭。开启后，新生成的 ZIP 资料包会尝试加入原始录音，会显著增加文件大小和准备时间。": "Off by default. When on, new ZIP packages try to include the original recording, which increases size and prep time.",
    "高级导出 / 给 Codex": "Advanced export / Codex",
    "通过系统分享面板 AirDrop、存储到文件或发到其他 App。导出副本不会改动原始录音。": "Share via AirDrop, Files, or another app. Exports are copies and do not change the original recording.",
    "选择资料包后才会准备音频并生成 ZIP；资料包默认包含转写文档和全部相关文件。是否包含原始录音由全局设置控制。": "Audio is prepared only after you choose a package. Packages include the transcript and related files; original audio follows the global setting.",
    "尚无可导出的文本。": "No text is available to export yet.",
    "尚无可用片段，无法生成字幕。": "No timed segments yet, so captions cannot be generated.",
    "没有可分享的音频。": "No audio is available to share.",
    "无法准备导出": "Couldn’t prepare the export",
    "无法准备音频分享。": "Couldn’t prepare audio for sharing.",
    "无法写入文本导出。": "Couldn’t write the text export.",
    "无法写入字幕导出。": "Couldn’t write the caption export.",
    # Settings / sync / privacy
    "同步": "Sync",
    "同步 Markdown 与 JSON 文档": "Sync Markdown and JSON documents",
    "公开 VoiceContext 文档（含文件夹归类元数据）；原始音频与明文声纹永不进入公开目录。iCloud 不可用时仍保存在本机。": "Public VoiceContext documents (including folder metadata). Original audio and raw voiceprints never enter the public folder. Files stay on-device if iCloud is unavailable.",
    "同步加密的已确认声纹档案": "Sync encrypted confirmed voiceprints",
    "AES-GCM 加密后写入私有 iCloud 路径；关闭同步时不保留云端档案。": "Encrypted with AES-GCM into a private iCloud path. Turning sync off does not keep a cloud copy.",
    "清除提示": "Dismiss",
    "任务与调度": "Jobs",
    "转写任务中心": "Transcription Jobs",
    "实时监控后台转写队列、分片推理状态与异常排障。": "Watch the on-device queue, segment status, and failures.",
    "Codex Skill": "Codex Skill",
    "会议纪要 Skill": "Meeting minutes skill",
    "仅 complete 会议可生成纪要；Skill 与模板写入本机 VoiceContext，iCloud 可用时再镜像。": "Only completed meetings can generate minutes. The skill and templates are written to on-device VoiceContext, then mirrored when iCloud is available.",
    "隐私与许可": "Privacy & Licenses",
    "录音和文稿默认保存在本机": "Recordings and transcripts stay on this device by default",
    "隐私与权限": "Privacy & Permissions",
    "第三方许可与归因": "Third-party licenses",
    "音频保留": "Audio retention",
    "默认 7 天": "7 days by default",
    "记录数": "Recordings",
    "开发验证": "Developer checks",
    "录音核心验证": "Recording core validation",
    "录音时自动记录地点": "Save location while recording",
    "开启后，仅在录音时获取一次当前位置并转换为中文地址保存在录音元数据中。你可以随时在录音详情中编辑或清空该地址。": "When on, location is read once at capture start and stored as an address on the recording. You can edit or clear it later in details.",
    # Onboarding / purchase
    "把一个念头，留在你的设备上。": "Keep a thought on your device.",
    "个人灵感、现场对话或一场会议，都从同一个“开始录音”进入。": "A passing idea, a live conversation, or a meeting all start from the same Record button.",
    "让 VoiceContext 听见你主动开始的记录。": "Let VoiceContext hear the recordings you start on purpose.",
    "拒绝权限后，你仍可浏览已有记录和文稿。": "If you decline, you can still browse existing recordings and transcripts.",
    "同步是可选的。关闭 iCloud 后，录音、转写、编辑和导出仍完整保留在本机。": "Sync is optional. With iCloud off, recording, transcription, editing, and export still work on this device.",
    "只同步完成后的文本与结构化文档；原始音频从不进入公开 iCloud Drive。": "Only finished text and structured documents sync. Original audio never enters public iCloud Drive.",
    "仅同步用户确认过的档案，并在同步前进行应用层加密。未经确认的声纹不会同步。": "Only confirmed profiles sync, and they are encrypted first. Unconfirmed voiceprints are not synced.",
    "公开文档与加密声纹同步相互独立。iCloud 不可用时，加密档案只保留在本机，不阻塞录音与转写。": "Document sync and encrypted voiceprint sync are independent. If iCloud is unavailable, archives stay on-device and never block recording.",
    "第 3 步，共 3 步": "Step 3 of 3",
    "第 1 步，共 3 步": "Step 1 of 3",
    "第 1 步，共 2 步": "Step 1 of 2",
    "首次打开后 3 天免费试用。": "3-day free trial from first launch.",
    "试用自首次打开应用起连续计时 72 小时；试用期满后可一次性永久解锁。具体价格以 App Store 显示为准。": "The trial runs 72 hours from first launch. After that you can unlock once, forever. Price is shown by the App Store.",
    "VoiceContext 不会自动监听。只有在你明确点按“开始录音”后，才会访问麦克风。": "VoiceContext never listens on its own. The microphone is used only after you tap Start Recording.",
    "录音边界": "Recording boundary",
    "本地处理": "On-device processing",
    "从「照片与视频」导入时，系统选择器只共享你选中的视频；应用会抽取音轨并在本地转写。": "When importing from Photos, the picker shares only the video you select. The app extracts audio and transcribes on-device.",
    "麦克风权限": "Microphone access",
    "位置与录音地点": "Location",
    "导入说明": "About importing",
    "不支持的格式会显示可读错误，且不会创建半残录音记录。": "Unsupported formats show a readable error and do not create a partial recording.",
    "以下归因与审核清单内置在 App 中，可离线查看。外部许可链接仅用于查阅原始文本；不会影响本地录音和文稿。": "Attribution and review notes are built into the app and work offline. External license links are only for reading the original text.",
    "继续后将显示系统麦克风权限请求": "Continue to the system microphone permission request",
    "进入下一步，不会开始录音": "Continue. Recording does not start yet.",
    "继续了解试用": "Continue to the trial",
    "免费试用": "Free trial",
    "解锁": "Unlock",
    "兑换优惠码": "Redeem code",
    "72 小时试用已到期": "The 72-hour trial has ended",
    "试用即将到期。": "The trial is ending soon.",
    "试用到期后仍可录音和保存音频；转写会等待永久解锁。": "After the trial you can still record and save audio. Transcription waits for a one-time unlock.",
    "这是一次性永久解锁，不是订阅。无业务服务器。": "This is a one-time unlock, not a subscription. There is no account server.",
    "这是一次性永久解锁，不是订阅。无业务服务器，100% 本地端侧隐私安全。": "This is a one-time unlock, not a subscription. No account server — processing stays on-device.",
    "一次性永久解锁 VoiceContext 全部功能（本地端侧 AI 转写、说话人识别与会议整理）。": "One-time unlock of VoiceContext: on-device transcription, speaker identification, and meeting organization.",
    "支持输入 App Store 兑换码直接解锁；原始录音文件保存在设备本机，可通过系统「文件」App 查阅与导出。": "You can redeem an App Store code. Original recordings stay on this device and can be opened in the Files app.",
    "暂时无法获取永久解锁商品，请稍后重试。": "Couldn’t load the unlock product. Try again in a moment.",
    "无法验证购买凭证。": "Couldn’t verify the purchase.",
    "未检测到有效购买。": "No valid purchase found.",
    "没有可恢复的购买。": "No purchases to restore.",
    "购买待批准，批准后将自动解锁。": "Purchase pending approval. Unlock happens after it is approved.",
    "未知购买结果": "Unknown purchase result",
    "您的原始音频与文稿完全储存在设备本地，不会丢失。在系统自带的「文件」App（我的 iPhone → VoiceContext）中可随时查阅与备份。": "Original audio and transcripts stay on this device. You can browse and back them up in the Files app (On My iPhone → VoiceContext).",
    "数据安全说明": "About your data",
    "使用条款": "Terms of Use",
    # Transcription center
    "转写任务中心": "Transcription Jobs",
    "当前分类下暂无任务": "No jobs in this category",
    "待处理": "Pending",
    "待完成": "To finish",
    "异常需关注": "Needs attention",
    "全部完成": "All done",
    "全部关停": "Cancel all",
    "重试异常": "Retry failures",
    "重新开始任务": "Restart jobs",
    "操作": "Actions",
    "当前没有失败的处理任务。": "There are no failed jobs.",
    "当前录音没有需要重试的任务。": "This recording has no jobs to retry.",
    "当前录音没有已取消的任务。": "This recording has no canceled jobs.",
    "当前没有可操作的录音。": "There is no recording to act on.",
    # Widget
    "轻点开录": "Tap to record",
    "轻点进入开录": "Tap to start recording",
    "正在录音": "Recording",
    "VoiceContext 正在录音": "VoiceContext is recording",
    "VoiceContext 录音已暂停": "VoiceContext recording paused",
    "一键进入开录流程。不显示逐字稿内容。": "Opens the recording flow. Transcript text is never shown on the widget.",
    "打开应用并进入开录流程": "Open the app and start recording",
    "在后台安全停止录音并保存分片": "Stop recording in the background and save the audio",
    "锁屏/控制中心停止入口": "Stop from Lock Screen / Control Center",
    # Weekdays
    "周日": "Sun",
    "周一": "Mon",
    "周二": "Tue",
    "周三": "Wed",
    "周四": "Thu",
    "周五": "Fri",
    "周六": "Sat",
    # Common errors / notices
    "导入失败": "Import failed",
    "搜索失败：": "Search failed: ",
    "选择文件失败：": "Couldn’t select the file: ",
    "没有可播放的音频分片。": "No playable audio segments.",
    "音频无法播放。": "Audio couldn’t be played.",
    "音频无法播放：所有分片都不可读。": "Audio couldn’t be played: no readable segments.",
    "麦克风权限未允许。你仍可浏览已有记录和文稿。": "Microphone access is off. You can still browse existing recordings and transcripts.",
    "未获得麦克风权限，无法开始录音。你仍可浏览记录；可在系统设置中允许麦克风。": "Microphone access is off, so recording can’t start. You can still browse recordings, or enable the microphone in Settings.",
    "未获得麦克风权限。": "Microphone access was not granted.",
    "前往系统设置": "Open Settings",
    "空间不足，本次未完成云端镜像。录音与本地文稿不受影响；清理空间后可重试同步。": "Not enough space to finish the cloud copy. Local recording and transcripts are fine. Free space and retry sync.",
    "网络中断导致同步未完成。本地录音、转写和导出仍可用。": "Sync didn’t finish because the network dropped. Local recording, transcription, and export still work.",
    "未登录 iCloud": "Not signed in to iCloud",
    "iCloud 容器不可用": "iCloud container unavailable",
    "iCloud 或磁盘空间不足": "Not enough iCloud or disk space",
    "文档仍保存在本机": "Documents remain on this device",
    "同步写入失败": "Sync write failed",
    "同步冲突，已保留双方副本": "Sync conflict — both copies were kept",
    "同步网络中断": "Sync network interrupted",
    "关闭同步无云档案": "Cloud copy removed when sync is off",
    "本地处理": "On-device",
    "公开文档": "Public documents",
    "本机公开目录": "On-device public folder",
    "模板": "Templates",
    "许可": "License",
    "归因": "Attribution",
    "查看许可原文": "View original license",
    "查看项目来源": "View project source",
    "应用内离线归因页": "In-app offline attribution",
    "设置页可离线浏览全部运行时与模型归因，不依赖网络。": "Settings can show every runtime and model attribution offline.",
    "欢迎": "Welcome",
    "继续引导且不开始录音": "Continue setup without recording",
    "不会请求麦克风，也不会开始录音": "Won’t ask for the microphone or start recording",
    "只请求权限，不会开始录音": "Asks for permission only — does not start recording",
    "尚未请求": "Not requested yet",
    "麦克风已允许": "Microphone allowed",
    "未允许；仍可浏览记录": "Not allowed; you can still browse recordings",
    "请求定位权限": "Request location access",
    "定位权限": "Location access",
    "清空地点": "Clear location",
    "输入录音发生的地址或地点（可选）": "Address or place (optional)",
    "编辑录音信息": "Edit recording info",
    "编辑录音信息…": "Edit recording info…",
    "输入标题": "Enter a title",
    "标签": "Tags",
    "标签与备注": "Tags & notes",
    "备忘录": "Memo",
    "输入的内容会自动保存到这条录音": "Edits save automatically to this recording",
    "保存名称": "Save name",
    "保存失败": "Couldn’t save",
    "保存校对": "Save proofreading",
    "保存说话人显示名称": "Save speaker name",
    "显示名称": "Display name",
    "显示名称不能为空。": "Display name can’t be empty.",
    "说话人显示名称": "Speaker name",
    "未知说话人": "Unknown speaker",
    "确认说话人": "Confirm speaker",
    "开始识别": "Start identification",
    "识别中": "Identifying",
    "提取中": "Extracting",
    "整理中": "Organizing",
    "整理": "Organize",
    "声文识别": "Voice matching",
    "声文整理": "Voice organization",
    "锁定": "Locked",
    "即将到期": "Ending soon",
    "转写试用": "Transcription trial",
    "首次打开后 72 小时": "72 hours after first launch",
    "首次打开后 72 小时内可试用，到期后可永久解锁。": "Try free for 72 hours after first launch, then unlock forever.",
    "首次打开应用后开始 72 小时试用；试用期内不按语音秒扣减。": "The 72-hour trial starts at first launch and is not billed per second of audio.",
    "已解锁，正在继续处理待转写音频。": "Unlocked. Continuing queued transcription.",
    "已重置 3 天试用倒计时": "Reset the 3-day trial countdown",
    "模拟商店离线": "Simulate store offline",
    "模拟恢复失败": "Simulate restore failure",
    # Format-style interpolations (SwiftUI / String(localized:))
    "已选择 %lld 条": "%lld selected",
    "删除(%lld)": "Delete (%lld)",
    "删除 %lld 条记录": "Delete %lld recordings",
    "%lld 条结果": "%lld results",
    "%lld 条记录": "%lld recordings",
    "%lld 条": "%lld",
    "已采集 %lld 个声纹特征向量": "%lld voice vectors enrolled",
    "版本 %lld": "Revision %lld",
    "%lld 分 %lld 秒": "%lld min %lld sec",
    "0 分 0 秒": "0 min 0 sec",
    "已跳过 %lld 个无法读取的分片。": "Skipped %lld unreadable segments.",
    "已就绪 %lld 个分句 · 正在增量转写后续音频 (%lld 个排队中)…": "%lld sentences ready · transcribing later audio (%lld queued)…",
    "%lld 个分片": "%lld segments",
    "还剩 %lld 项": "%lld remaining",
    "该日期共有 %lld 条录音": "%lld recordings on this day",
    "确定要删除选中的 %lld 条录音吗？将同时清除关联的本地音频文件与转写文稿，且无法恢复。": "Delete the %lld selected recordings? Local audio and transcripts will be removed and cannot be recovered.",
    "已重新排队 %lld 个失败任务。": "Requeued %lld failed jobs.",
    "已重新排队 %lld 个转写分段。": "Requeued %lld transcription segments.",
    "已重新开始 %lld 个已取消的转写任务。": "Restarted %lld canceled transcription jobs.",
    "正在抽取音轨 %lld%%：%@": "Extracting audio %lld%%: %@",
    "正在准备导入：%@": "Preparing import: %@",
    "正在导入：%@": "Importing: %@",
    "导入失败：%@": "Import failed: %@",
    "搜索失败：%@": "Search failed: %@",
    "选择文件失败：%@": "Couldn’t select the file: %@",
    "文件夹：%@": "Folder: %@",
    "说话人 %lld": "Speaker %lld",
    "已转写至 +%@": "Transcribed to +%@",
}


def build_catalog() -> dict:
    strings = {}
    for zh, en in TRANSLATIONS.items():
        strings[zh] = {
            "extractionState": "manual",
            "localizations": {
                "en": {
                    "stringUnit": {
                        "state": "translated",
                        "value": en,
                    }
                }
            },
        }
    return {
        "sourceLanguage": "zh-Hans",
        "strings": strings,
        "version": "1.0",
    }


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    out = root / "speech_note" / "speech_note" / "Localizable.xcstrings"
    out.write_text(json.dumps(build_catalog(), ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {out} ({len(TRANSLATIONS)} strings)")


if __name__ == "__main__":
    main()
